### ISSUE TITLE
Replace express with fastify

### ISSUE THREAD

**Issue by windbeneathyourwings** [ng-druid/platform#202]
AWS lambda server-side rendering for Angular using express leaves much to be desired in terms of performance. Can fastify remedy this problem?

https://github.com/fastify/fastify

https://github.com/exequiel09/fastify-angular-universal

Pre-rendering is also another option once server-side rendering data wait for issues are sorted out. Probably better to devote time to that than this because pre-rendering with physical page data would make it possible to serve the app on cdn rather than lambda which nullifies the need for a server anyway. Except in the case of proxies to aws services. However, there are probably other work-arounds for that as well to add the proper cors headers or worst comes to worst create dedicated proxy lambda as simple lambda using either express or fastify.

**Comment by ng-druid** [comment]
This isn’t really necessary to improve speed now that pages can be pre rendered.
